version: '3.9'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "valun"
      POSTGRES_PASSWORD: 123
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"