"""add users and roles

Revision ID: 7162ed073b92
Revises: 
Create Date: 2023-10-18 09:52:27.223033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7162ed073b92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# методы, которые выполняются в этой миграции (roles, users)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ondelete="SET NULL"), #дописали ручками SET NULL
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    
# DELETE FROM public.roles
# WHERE id=1;

# DELETE FROM public.users
# WHERE id in (1, 10, 11, 12, 13, 14, 15, 16);

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
